path:
  train_path: ../data/train.csv
  test_path: ../data/dev.csv
  predict_path: ../data/test.csv
  save_path: save_models/

data:
  shuffle: True
  train_ratio: 0.8
  swap: True

model:
  model_name: klue/roberta-large

train:
  max_epoch: 100
  batch_size: 32
  learning_rate: 6e-6
  loss: mse
  use_frozen: False
  
utils:
  seed: 42
  monitor: val_pearson
  patience: 20
  top_k: 3

k_fold:
  use_k_fold: False
  num_folds: 10
  num_split: 10
  
wandb:
  project: roberta-large